version: "3.8"

services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users_service
    ports:
      - "3005:3005"
    environment:
      DB_HOST: users_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: project_modernization_users
      DB_TYPE: postgresql
      APP_ENV: dev
    depends_on:
      - users_db

  users_db:
    image: postgres:15
    container_name: users_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_modernization_users
    ports:
      - "5434:5432"
    volumes:
      - users_pgdata:/var/lib/postgresql/data

volumes:
  users_pgdata:
